# cloudbuild.yaml
steps:
  # 缓存构建依赖
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker pull gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest || exit 0
    id: 'pull-cache'

  # 多阶段构建
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest',
      '.'
    ]
    id: 'build-image'
    waitFor: ['pull-cache']

  # 推送镜像
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest']
    id: 'push-image'

  # 部署到 Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', '${_SERVICE_NAME}',
      '--image', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest',
      '--region', '${_REGION}',
      '--platform', 'managed',
      '--port', '8501',
      '--memory', '${_MEMORY}',
      '--cpu', '${_CPU}',
      '--max-instances', '${_MAX_INSTANCES}',
      '--min-instances', '${_MIN_INSTANCES}',
      '--timeout', '3600',
      '--concurrency', '80',
      '--set-env-vars', '${_VAR}',
      '--allow-unauthenticated',
      '--tag', '${_ENVIRONMENT}'
    ]
    id: 'deploy'



substitutions:
  _SERVICE_NAME: 'default-service'
  _REGION: 'us-east1'
  _ENVIRONMENT: 'staging'
  _MEMORY: '2Gi'
  _CPU: '1'
  _MAX_INSTANCES: '2'
  _MIN_INSTANCES: '1'
  _VAR: ''


options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  substitutionOption: 'ALLOW_LOOSE'

timeout: '1800s'